# Generated by Django 5.0.3 on 2024-03-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
    ]
